import dotenv from "dotenv";
dotenv.config();
export const PORT = process.env.PORT || 5000;
export const SECRET_KEY = process.env.JWT_SECRET;
export const NODE_ENV = process.env.NODE_ENV;
export const CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME!;
export const API_KEY = process.env.CLOUDINARY_API_KEY!;
export const API_SECRET = process.env.CLOUDINARY_API_SECRET!;
export const EMAIL_USER = process.env.EMAIL_USER!;
export const EMAIL_PASS = process.env.EMAIL_PASS!;
export const BASE_URL = process.env.BASE_URL;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
